server:
  port: 8083

spring:
  application:
    name: ingame-service
  datasource:
    url: jdbc:mysql://localhost:3306/gwent?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

gwent:
  security:
    jwt:
      jwks-uri: http://localhost:8085/.well-known/jwks.json
  services:
    jugador:
      name: jugador-service
      base-url: http://localhost:8082
      match-result-url: /api/v1/players/match-result

springdoc:
  packages-to-scan: com.arimar.gwent.ingameservice

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

logging:
  level:
    org.springframework.security: DEBUG
    com.arimar.gwent.ingameservice.service: DEBUG
